spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/blogengine?allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=UTC&useSSL=false&verifyServerCertificate=false
    username: root
    password: 3s5a6dslipknot
  flyway:
    locations=classpath:
      db/migration/V1__create_blog.sql
    enabled: false
  jpa:
    show-sql: false
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

blog:
  title: DevPub
  subtitle: Минутка щедрости разработчиков
  phone: +7 999 532-77-10
  email: newmail@mail.ru
  copyright: Андреев Иннокентий
  copyrightFrom: 2020